# Generated by Django 4.2.6 on 2023-10-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesaler',
            old_name='saler_name',
            new_name='name',
        ),
    ]
