# Generated by Django 4.2.6 on 2023-10-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_producttypequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
