# Generated by Django 4.2.6 on 2023-10-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
