# Generated by Django 4.2.6 on 2023-10-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_client_date_of_birth_remove_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('exchange', 'Exchange')], max_length=8)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(blank=True, choices=[('percent', 'Percentage'), ('amount', 'Amount')], max_length=8, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
